### ISSUE TITLE
Empty assignee is included in request for creating new issue

### ISSUE THREAD

**Issue by Programie** [lesstif/php-jira-rest-client#126]
I want to create an issue without an assignee set but JIRA responds with an error 400 "Field 'assignee' cannot be set. It is not on the appropriate screen, or unknown".

I debugged the code a bit and saw that the JSON sent to the JIRA API includes an "assignee" field set to null.

PHP: 7.1.7
JIRA: 7.2.3
PHP JIRA Rest Client: 1.18.1

**Comment by lesstif** [comment]
If your JIRA instance set to 'Allow unassigned issues' then null assignee value means that the this issue have no assignee.

If JIRA is set so that don't allow unassigned issue, then it is a logical error. so you must modify the issue registration code to have assignee.

you can modify 'unassigned issue' policy, login to admin and Administration --> General Configuration -> 'Allow unassigned issues' option.

thanks.

**Comment by lesstif** [comment]
On second thought, you're right.

it was fixed at [v1.19.1](https://github.com/lesstif/php-jira-rest-client/releases/tag/1.19.1)

thanks!
