### ISSUE TITLE
sprint # committed and sprint carryover totals?

### ISSUE THREAD

**Issue by fuel-lhartwell** [lesstif/php-jira-rest-client#91]
I'm trying to find a way to get the sprint total number committed, completed, and carryover. Is that possible using your library?

What I need is the numbers that can be found on the Sprint Velocity report
https://<YOURURL>.atlassian.net/secure/RapidBoard.jspa?projectKey=ALLERGY&rapidView=<rapidviewID>&view=reporting&chart=velocityChart

**Comment by lesstif** [comment]
currently, this library does not supported sprint features.

**Comment by donkidd** [comment]
@fuel-lhartwell I have started by adding the ability to get info by sprint into the library.  What you are asking for is what I ultimately need, so I hope to look into it in the next few weeks but I can't promise when I'll get it all working.

**Comment by donkidd** [comment]
@fuel-lhartwell I don't see carryover in the report I have.  I am using 
rest/greenhopper/1.0/rapid/charts/velocity.json?rapidViewId=307&sprintId=687
From there I can get committed and completed, how important is carryover?  It might be obtainable from somewhere else, just wondering since that URL isn't nicely parsable. do you happen to know the URL for a WS behind that report?
